version: '3.6'

volumes:
  mongodb_data:
    driver: local
   
services:
  mongodb:
    image: mongodb/mongodb-community-server
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    
  rest_patient:
    image: jjnius/rest_patient
    container_name: rest/patient
    build: ./PatientRestApi
    ports:
      - "5301:5301"

  grpc_country:
    image: jjniuss/grpc_country
    container_name: grpc/country
    build: 
      context: Clinic.CountryService
      dockerfile: Clinic-Dictionary-Dockerfile
    ports:
      - "5302:5302"
    depends_on:
      - mongodb

  rest_identity:
    image: jjniuss/rest_identity
    container_name: rest/identity
    build:  
      context: Clinic.Identity
      dockerfile: Clinic-Identity-Dockerfile
    ports:
      - "5303:5303"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5303
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    command: start-dev
    environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://172.24.160.1:5432/Clinic.Identity
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: jnius
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "27018:27018"
